# Generated by Django 6.0.4 on 2026-04-16 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short headline e.g. "Calculus tutoring for first-years"', max_length=120)),
                ('description', models.TextField(help_text='Longer explanation of what you offer, your experience, etc.')),
                ('category', models.CharField(choices=[('tutoring', 'Tutoring'), ('design', 'Design & Creative'), ('coding', 'Coding & Tech'), ('writing', 'Writing & Editing'), ('music', 'Music Lessons'), ('fitness', 'Fitness & Wellness'), ('moving', 'Moving & Errands'), ('other', 'Other')], default='other', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank if this is a free service.', max_digits=6, null=True)),
                ('is_free', models.BooleanField(default=False, help_text='Tick if you offer this for free.')),
                ('contact_preference', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone / Text'), ('discord', 'Discord'), ('inperson', 'In Person')], default='email', max_length=20)),
                ('is_available', models.BooleanField(default=True, help_text='Untick to temporarily hide this skill from the public list.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
